### PR TITLE
This merge fixes the occasional hanging i experience with the multi threaded code

### PR DESCRIPTION
**Pull request by djpiper28**

### CODE REVIEW

**Comment by antag99** [comment]
Nice, could you squash the 5 commits into one as described in the StackOverflow answer at https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git#5201642 ?

**Comment by djpiper28** [comment]
I have squashed the commits

**Comment by antag99** [comment]
Seems like you ended up with 7 commits instead, maybe you need a force push to your remote branch after having added made the squash locally, rather than merging from the remote before pushing? (`git push --force origin master`).

**Comment by djpiper28** [comment]
I squashed locally which caused there to be so many commits, I have forced the push and it is one commit now.

**Pull request merged**
